

DROP SEQUENCE IF EXISTS NUMTICKET_SEQUENCE;

CREATE SEQUENCE NUMTICKET_SEQUENCE 
START WITH 0 INCREMENT BY 1;


/*
Admin users
*/
INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, NULL, NULL, 'admin@admin.com', NULL, TRUE, 'Don Bosco', '$2a$10$sbNAUG/zX5oRekmEWKP0A.1rYn/86YiOnxjaje2vVccxNDm98tBP6', '654987327', SYSDATE, NULL, 'admin' );

INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, TO_DATE('22/03/1997', 'DD/MM/YYYY'), NULL, 'jmbargueno@admin.com', 'H', TRUE, 'Jose Manuel', '$2a$10$8pHfjdq8zHKT6e8TqHM/iOSV2plG1cM/3fsOqh5MGqUq4NNCRL.AW', '654987328', SYSDATE, NULL, 'jmbargueno' );

/*
Non Admin Users
*/

INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, NULL, NULL, 'usuario@usuario.com', NULL, FALSE, 'Broncano', '$2a$10$8pHfjdq8zHKT6e8TqHM/iOSV2plG1cM/3fsOqh5MGqUq4NNCRL.AW', '654987329', SYSDATE, NULL, 'usuario' );

INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, NULL, NULL, 'usuario1@usuario.com', NULL, FALSE, 'Daniel', '$2a$10$8pHfjdq8zHKT6e8TqHM/iOSV2plG1cM/3fsOqh5MGqUq4NNCRL.AW', '654987328', SYSDATE, NULL, 'daniel' );

INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, NULL, NULL, 'usuario2@usuario.com', NULL, FALSE, 'Mario', '$2a$10$8pHfjdq8zHKT6e8TqHM/iOSV2plG1cM/3fsOqh5MGqUq4NNCRL.AW', '654987327', SYSDATE, NULL, 'mario' );

INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, NULL, NULL, 'usuario3@usuario.com', NULL, FALSE, 'Tere', '$2a$10$8pHfjdq8zHKT6e8TqHM/iOSV2plG1cM/3fsOqh5MGqUq4NNCRL.AW', '654987326', SYSDATE, NULL, 'tere' );

INSERT INTO USERFA
    (ID, BIRTHDAY, DNI, EMAIL, GENDER, IS_ADMIN, NAME, PASSWORD, PHONE_NUMBER, REGISTER_DATE, SURNAME, USERNAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, NULL, NULL, 'usuario4@usuario.com', NULL, FALSE, 'javi', '$2a$10$8pHfjdq8zHKT6e8TqHM/iOSV2plG1cM/3fsOqh5MGqUq4NNCRL.AW', '654987325', SYSDATE, NULL, 'javi' );
/*
Consumables
*/
INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Larios', 'Pack de botella Larios con 6 refrescos', 60, 20, 'Larios');

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Larios +', 'Pack de 2 botellas de Larios con 12 refrescos y cachimba', 120, 20, 'Larios');


INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Legendario', 'Pack de botella Legendario con 6 refrescos', 60, 20, 'Legendario');

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Legendario +', 'Pack de 2 botellas de Legendario con 12 refrescos y cachimba', 120, 20, 'Legendario');


INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Jäger', 'Pack de botella Jägermeister con 6 refrescos', 80, 10, 'Jager');

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Jäger +', 'Pack de 2 botellas de Jägermeister con 12 refrescos y cachimba', 160, 20, 'Jager');

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack JägerBomb', 'Pack de 1 botellas de Jägermeister con 6 Redbulls y cachimba', 90, 20, 'Jager');

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, MARK)
VALUES
    ('C', HIBERNATE_SEQUENCE.NEXTVAL, 'Pack Moetbomb', 'Pack de botella Moet con 8 Redbulls', 100, 10, 'Moet');

/*
Reservado sin fechas
*/
INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_PERSONS, NUM_VIP)
VALUES
    ('V', HIBERNATE_SEQUENCE.NEXTVAL, 'Reservado Olimpo', 'Sientete como los dioses', 10, 200, NULL, 5, 5);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_PERSONS, NUM_VIP)
VALUES
    ('V', HIBERNATE_SEQUENCE.NEXTVAL, 'Reservado Roma', 'Sientete como un César', 10, 200, NULL, 5, 5);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_PERSONS, NUM_VIP)
VALUES
    ('V', HIBERNATE_SEQUENCE.NEXTVAL, 'Reservado Inferno', 'Al lado de la pista, se un diablo', 10, 200, NULL, 5, 5);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_PERSONS, NUM_VIP)
VALUES
    ('V', HIBERNATE_SEQUENCE.NEXTVAL, 'Reservado Heaven', 'El de la planta de arriba con vistas', 10, 200, NULL, 5, 5);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_PERSONS, NUM_VIP)
VALUES
    ('V', HIBERNATE_SEQUENCE.NEXTVAL, 'Reservado Shot', 'Con phocall privado', 10, 200, NULL, 5, 5);

/*
Reservados con fecha
*/
INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_PERSONS, NUM_VIP)
VALUES
    ('V', HIBERNATE_SEQUENCE.NEXTVAL, 'Reservado Pompadur', 'El mejor reservado de todos', 10, 200, TO_DATE('01/06/2019', 'DD/MM/YYYY'), 5, 5);




/*
Tickets
*/
INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Sábado Night Bull', 'Ticket Sabado noche', 10, 200, TO_DATE('01/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Miércoles Funky Night', 'Este evento reune a los mejores grupos de baile Funky en nuestra sala, ¡No te lo pierdas!', 20, 173, TO_DATE('12/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Jueves', 'Este evento reune a los mejores grupos de baile Funky en nuestra sala, ¡No te lo pierdas!', 20, 173, TO_DATE('13/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Viernes Night', 'Este evento reune a los mejores grupos de baile Funky en nuestra sala, ¡No te lo pierdas!', 20, 173, TO_DATE('15/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Sabado Fever', 'Este evento reune a los mejores grupos de baile Funky en nuestra sala, ¡No te lo pierdas!', 20, 173, TO_DATE('16/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Sunday', 'Este evento reune a los mejores grupos de baile Funky en nuestra sala, ¡No te lo pierdas!', 20, 173, TO_DATE('17/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);

INSERT INTO PRODUCT
    (DTYPE, ID, NAME, DESCRIPTION, PRICE, STOCK, EVENT_DATE, NUM_TICKET)
VALUES
    ('T', HIBERNATE_SEQUENCE.NEXTVAL, 'Monday Relax', 'Este evento reune a los mejores grupos de baile Funky en nuestra sala, ¡No te lo pierdas!', 20, 173, TO_DATE('18/06/2019', 'DD/MM/YYYY'), NUMTICKET_SEQUENCE.NEXTVAL);
/*
Events
*/
INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Nuestra primera fiesta vip, no deberias perderte esta fiesta de apertura.', NULL, 'Mensual Vip Party I', TO_DATE('01/06/2019', 'DD/MM/YYYY'));


INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Ya disponible entradas de uno de nuestros eventos con mayor rango de clientes, pillalas rápido que se acaban! PD: Recuerda que el disfraz es OBLIGATORIO', NULL, 'Navidad', TO_DATE('31/10/2019', 'DD/MM/YYYY'));

INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Disponible', NULL, 'Año nuevo', TO_DATE('01/11/2019', 'DD/MM/YYYY'));

INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Disponible ya', NULL, 'PostExamenes', TO_DATE('20/07/2019', 'DD/MM/YYYY'));

INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Disponible ya', NULL, 'San Juan', TO_DATE('23/06/2019', 'DD/MM/YYYY'));

INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Disponible ya', NULL, 'El dia 1', TO_DATE('01/08/2019', 'DD/MM/YYYY'));

INSERT INTO EVENT
    (ID, DESCRIPTION, IMG_URL, NAME, EVENT_DATE)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Disponible ya', NULL, 'PreWork', TO_DATE('09/09/2019', 'DD/MM/YYYY'));
/*
PartyTypes
*/
INSERT INTO PARTY_TYPE
    (ID, DESCRIPTION, IMG_URL, NAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Nuestra fiesta mensual, la que te quita todo lo chungo de la mente', NULL, 'Mensual Vip Party');

INSERT INTO PARTY_TYPE
    (ID, DESCRIPTION, IMG_URL, NAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'La mejor fiesta de verano, solo 2 al año, todos de blanco, para quedarte blanco', NULL, 'La Ibicenca');

INSERT INTO PARTY_TYPE
    (ID, DESCRIPTION, IMG_URL, NAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Nuestra mitiquísima fiesta de Halloween, apúntate si quieres pasar una noche terriblemente divertida. Por cierto, si no vas disfrazado, no entras ;)', NULL, 'Licorween');
INSERT INTO PARTY_TYPE
    (ID, DESCRIPTION, IMG_URL, NAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, 'Nuestra mitiquísima fiesta San Juana', NULL, 'San Juana Party');

    INSERT INTO PARTY_TYPE
    (ID, DESCRIPTION, IMG_URL, NAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, '¿¡Queda poco!', NULL, 'PreworkParty');

    INSERT INTO PARTY_TYPE
    (ID, DESCRIPTION, IMG_URL, NAME)
VALUES
    (HIBERNATE_SEQUENCE.NEXTVAL, '¡Bienvenido al nuevo año!', NULL, 'Final Age');